#if !canImport(ObjectiveC)
import XCTest

extension ReinforceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReinforceTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReinforceTests.__allTests__ReinforceTests),
    ]
}
#endif
